setwd('~/Desktop/Spring 2016/Data Mining/project/')
library(linkcomm)
head(lesmiserables)
frame <- 
lc <- getLinkCommunities(lesmiserables, hcmethod = "single")
plot(lc, type = "graph", layout = layout.fruchterman.reingold)
plot(lc, type = "graph", layout = "spencer.circle")
plot(lc, type = "graph", layout = "spencer.circle", shownodesin = 3)
plot(lc, type = "members")
cc <- getCommunityCentrality(lc)
head(sort(cc, decreasing = TRUE))
head(lc$numclusters)
cm <- getCommunityConnectedness(lc, conn = "modularity")
plot(lc, type = "commsumm", summary = "modularity")
